Add currentLocation feature in the 'Expanding Network' section
JoyMonteiro/bharatsim-tutorial pull request #39
Opened 2024-06-12 20:16 UTC by RushilGupta4

2024-06-13 03:47 UTC, dpcherian requested changes
Good work! I've added a couple of simple changes that need to be made before merging, could you get them done? Thanks!

2024-06-13 03:47 UTC, dpcherian commented on source/firstprogram-expanding-network.rst
> +Now, we also need to handle the location of the individual at every step to ensure that the individual is only in contact with the people in the same location. This is done by adding a new ``currentL
Typeset class names with backticks and correct capitalisation: for example, 

> [...] in the ``Person`` class.

2024-06-13 03:47 UTC, dpcherian commented on source/firstprogram-expanding-network.rst
> +Now, we also need to handle the location of the individual at every step to ensure that the individual is only in contact with the people in the same location. This is done by adding a new ``currentL
We haven't used ideas like "constructors" yet, could you say something that would be a little more clear to novice users like:

> In order to implement this, we add a new attribute to the ``Person`` class called ``currentLocation`` which stores the exact current location of the agent. This attribute has to be dynamically updated at every time-step based on the agent's schedule. This is done by adding a new behaviour <add a local link here to the section on agents and behaviours> ``updateCurrentLocation``. This is implemented below.

2024-06-13 03:47 UTC, dpcherian commented on source/firstprogram-expanding-network.rst
> +      Some(placeType)
Could you add one line below this explaining what ``Option`` and ``Some`` mean? Nothing too elaborate, just a small description like from the link you sent me (https://stackoverflow.com/questions/49944872/understanding-some-and-option-in-scala). Add a link to some online documentation on this as well, if possible.

2024-06-13 03:47 UTC, dpcherian commented on source/firstprogram-expanding-network.rst
> +We then also need to update the ``checkForInfection`` function to only check for infections in the same location. We start by counting the total number of people in the Person's current location, and
Add one line here explaining what would go wrong if we didn't do this (everyone linked to a node would be considered, even if they were home).

2024-07-09 03:57 UTC, RushilGupta4 commented
I have made the changes. Could you go over them once?

2024-07-09 16:14 UTC, merged