Installation and Setup Instructions for IntelliJ Idea and VSCode
JoyMonteiro/bharatsim-tutorial pull request #5
Opened 2021-08-13 15:51 UTC by TheReconPilot

- Wrote a brief intro on the `index.rst` file.
- Added installation and setup instructions in `setup.rst`.
- Put images in `source/_static/images`

2021-08-13 18:21 UTC, TheReconPilot commented
Added some content on command line.

2021-08-16 08:17 UTC, dpcherian requested changes
The actual BharatSim source code directory will probably just be called ``BharatSim``, and not ``BharatSim-master`` which was just a name of the downloaded repository we sent you guys. Could you change this document to reflect that?

We will include a dummy data file with the repository, so you don't need to include how to generate the dummy data here. Just work under the assumption that an appropriately named file is placed in the correct place. (You can keep the error message, but put in an explanation saying that a file called ``citizen10k.csv` should exist in the appropriate folder, in case someone deletes it by accident.) It is an important thing to describe, just not here. I would suggest putting that in a separate section, I've added a section under Miscellaneous in the Google Sheet.

2021-08-16 09:36 UTC, TheReconPilot commented
Ah okay. Will do the changes and commit soon.

2021-08-16 10:27 UTC, TheReconPilot commented
Made the changes

2021-08-16 11:01 UTC, dpcherian reviewed
Overall looks great, good work. Mentioned some changes that might be good to implement in the images. See if you can add them?

2021-08-16 13:19 UTC, TheReconPilot commented on source/setup.rst
> +    .. image:: _static/images/cli-sir-run.png
Fixed in 770fc28

2021-08-16 13:20 UTC, TheReconPilot commented on source/setup.rst
> +  .. image:: _static/images/sbt-console.png
Fixed in 770fc28

2021-08-16 13:21 UTC, TheReconPilot commented on source/setup.rst
> +    .. image:: _static/images/sir-run.png
Yeah that was a particularly bad screenshot. I switched to a better tool now. 

Fixed in aac8b5a

2021-08-16 13:21 UTC, TheReconPilot commented on source/setup.rst
> +    .. image:: _static/images/vscode-sir-run.png
Fixed in aac8b5a

2021-08-16 13:22 UTC, TheReconPilot commented on source/setup.rst
> +  * Unzip the archive: ``tar xvf archivename.tar.gz``.
Done on 4ef5821

2021-08-16 17:52 UTC, dpcherian approved these changes
Looks great! Thanks for making the changes, I'm approving the pull-request.

2021-08-16 17:53 UTC, merged